import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import request from 'supertest';
import {migrateLocal} from '../db/migrate.js';
import {seed} from '../db/seed.js';
import {createApp} from '../src/app.js';
import {processSimulation} from '../src/orders.js';
let raw,db,app,a,b,csrfA,csrfB,userA,product,order;
const origin='http://localhost:3000';
before(async()=>{raw=new PGlite();await migrateLocal(raw);db={query:(q,v=[])=>raw.query(q,v),transaction:fn=>raw.transaction(fn),local:true};await seed(db);app=createApp(db,{origin});a=request.agent(app);b=request.agent(app);product=(await db.query('SELECT id FROM products WHERE supplier_code=$1',['DEMO-ML86'])).rows[0].id;});
after(async()=>raw.close());
const post=(agent,path,csrf,body)=>agent.post('/api'+path).set('Origin',origin).set('X-CSRF-Token',csrf||'').send(body||{});
test('catalog public; orders and admin protected',async()=>{assert.equal((await request(app).get('/api/catalog')).status,200);assert.equal((await request(app).get('/api/orders')).status,401);assert.equal((await request(app).get('/api/admin/orders')).status,401);});
test('register does not accept injected admin role; password stored as hash',async()=>{let r=await post(a,'/auth/register',null,{email:'a@example.test',password:'Test-only-password-123',name:'Customer A',role:'admin'});assert.equal(r.status,201);csrfA=r.body.csrf;userA=r.body.user.id;assert.equal(r.body.user.role,'customer');assert.match(r.headers['set-cookie'][0],/HttpOnly/);r=await post(b,'/auth/register',null,{email:'b@example.test',password:'Test-only-password-456',name:'Customer B'});csrfB=r.body.csrf;assert.equal(r.status,201);assert.equal((await a.get('/api/admin/orders')).status,403);const u=(await db.query('SELECT password_hash FROM users WHERE id=$1',[userA])).rows[0];assert.notEqual(u.password_hash,'Test-only-password-123');});
test('reject forged origins, missing CSRF, missing server ID',async()=>{assert.equal((await a.post('/api/orders').set('Origin','https://evil.test').send({})).status,403);assert.equal((await a.post('/api/orders').set('Origin',origin).send({})).status,403);assert.equal((await post(a,'/orders',csrfA,{items:[{productId:product,targetId:'123456'}]}).set('Idempotency-Key','test-request-0001')).status,400);});
test('server prices checkout and binds idempotency to body',async()=>{const body={total:1,items:[{productId:product,targetId:'123456789',serverId:'1234',price:1}]};let r=await post(a,'/orders',csrfA,body).set('Idempotency-Key','test-request-0002');assert.equal(r.status,201);order=r.body;assert.equal(order.total,21000);r=await post(a,'/orders',csrfA,body).set('Idempotency-Key','test-request-0002');assert.equal(r.body.id,order.id);r=await post(a,'/orders',csrfA,{items:[{productId:product,targetId:'999999',serverId:'1234'}]}).set('Idempotency-Key','test-request-0002');assert.equal(r.status,409);});
test('another customer cannot read or pay an order',async()=>{assert.equal((await b.get('/api/orders/'+order.id)).status,404);assert.equal((await post(b,'/orders/'+order.id+'/simulate-payment',csrfB)).status,404);});
test('duplicate payment only queues once; worker fulfills once without deposit',async()=>{assert.equal((await post(a,'/orders/'+order.id+'/simulate-payment',csrfA)).status,200);assert.equal((await post(a,'/orders/'+order.id+'/simulate-payment',csrfA)).status,200);assert.equal((await db.query('SELECT * FROM fulfillment_jobs WHERE order_id=$1',[order.id])).rows.length,1);await processSimulation(db);assert.equal(await processSimulation(db),false);const d=await a.get('/api/orders/'+order.id);assert.equal(d.body.fulfillment_status,'success');assert.equal(d.body.items[0].cost,undefined);assert.equal((await db.query('SELECT balance FROM supplier_settings WHERE id=1')).rows[0].balance,500000);assert.equal((await db.query('SELECT * FROM supplier_ledger WHERE order_id=$1',[order.id])).rows.length,0);});
test('zero legacy balance does not block paid orders; products and game filters',async()=>{
 await db.query('UPDATE supplier_settings SET balance=0 WHERE id=1');
 const r=await post(a,'/orders',csrfA,{items:[{productId:product,targetId:'123456789',serverId:'1234'}]}).set('Idempotency-Key','test-request-0003');
 assert.equal(await processSimulation(db),false);
 await post(a,'/orders/'+r.body.id+'/simulate-payment',csrfA);await processSimulation(db);
 assert.equal((await a.get('/api/orders/'+r.body.id)).body.fulfillment_status,'success');
 await db.query("UPDATE users SET role='admin' WHERE id=$1",[userA]);
 assert.equal((await post(a,'/admin/supplier/deposit',csrfA,{amount:50000})).status,404);
 const body={gameId:'free-fire',name:'70 Diamonds',supplierCode:'DEMO-FF70-TEST',cost:8000,price:10000,active:true};
 assert.equal((await post(b,'/admin/products',csrfB,body)).status,403);
 const created=await post(a,'/admin/products',csrfA,body);assert.equal(created.status,201);
 assert.equal((await post(a,'/admin/products',csrfA,body)).status,409);
 assert.equal((await post(a,'/admin/products',csrfA,{...body,gameId:'missing',supplierCode:'MISSING'})).status,400);
 const products=await a.get('/api/admin/products?game=free-fire');assert.ok(products.body.every(p=>p.game_id==='free-fire'));assert.ok(products.body.some(p=>p.id===created.body.id));
 const mixed=await post(b,'/orders',csrfB,{items:[{productId:product,targetId:'123456',serverId:'1234'},{productId:created.body.id,targetId:'987654'}]}).set('Idempotency-Key','mixed-game-order-0001');
 await post(b,'/orders/'+mixed.body.id+'/simulate-payment',csrfB);await processSimulation(db);
 const dash=(await a.get('/api/admin/dashboard?game=free-fire')).body;assert.equal(Number(dash.summary.received),10000);assert.equal(dash.summary.orders,1);assert.equal(dash.sales.length,30);assert.equal(dash.sales.reduce((n,r)=>n+Number(r.revenue),0),10000);assert.equal(dash.sales.reduce((n,r)=>n+r.orders,0),1);const empty=(await a.get('/api/admin/dashboard?game=pubg-mobile')).body;assert.ok(empty.sales.every(r=>Number(r.revenue)===0&&r.orders===0));
 const shipments=(await a.get('/api/admin/supplier?game=free-fire')).body;assert.equal(shipments.length,1);assert.equal(shipments[0].product_name,'70 Diamonds');assert.equal(shipments[0].target_id,'987654');assert.equal(shipments[0].processed_by,'Sistem otomatis (simulasi)');
});
test('expired orders cannot be paid; logout invalidates session',async()=>{const r=await post(b,'/orders',csrfB,{items:[{productId:product,targetId:'123456789',serverId:'1234'}]}).set('Idempotency-Key','test-request-0004');await db.query("UPDATE orders SET expires_at=now()-interval '1 minute' WHERE id=$1",[r.body.id]);assert.equal((await post(b,'/orders/'+r.body.id+'/simulate-payment',csrfB)).status,409);assert.equal((await b.get('/api/orders/'+r.body.id)).body.payment_status,'expired');await post(b,'/auth/logout',csrfB);assert.equal((await b.get('/api/orders')).status,401);});
